### PR TITLE
I added a basic README file

### LINKED ISSUE #8: Create Readme file
Create a markdown readme file, providing details of the project - All About Trees

### PR DESCRIPTION
**Pull request by HerbertHomolka1**
I added a basic README.md file which provides a short describtion of our project.
It will however still have to be edited later. 
I have edited the marked sections:
- [x] general info
- [x] technologies
- [ ] code examples
- [ ] features
- [ ] contact
- [ ] status
- [ ] inspiration
- [ ] screenshot

Closes #8

## General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### HTML

- [ ] pages besides `/index.html` are stored in `/pages`
- [ ] the code is well-formatted
- [ ] the HTML is valid
- [ ] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [ ] semantic tags are used
- [ ] spelling and grammar is correct in all site content

### CSS

- [ ] the code is well-formatted
- [ ] passes all the linting checks

### CODE REVIEW

**Review by amanuel-zemikael — COMMENTED** [review]
edit and re create again

**Comment by HerbertHomolka1** [comment]
Here is the screenshot of the previous error.
I fixed it by running format:check which I had forgotten before. 
The new commit fixed it.

**Review by amanuel-zemikael — DISMISSED** [review]

**Review by HerbertHomolka1 — COMMENTED** [review]
The commit in which I added the communication.md ... 
I should add it in another issue.

**Comment by HerbertHomolka1** [comment]
It should be good now. Sorry it took so long

**Pull request merged**
